# Generated by Django 4.0.6 on 2022-07-26 15:59

from django.db import migrations, models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Date_of_Birth',
            field=models.DateField(auto_now=True, null=tkinter.tix.Tree),
            preserve_default=tkinter.tix.Tree,
        ),
    ]
